#pragma once


#include "../CoreHelper.h"
#include "DArgument.h"


//DeferredListener 기본 ArgType
#define DEFERRED_LISTENER_BASE_ARG DEFINE_ARG_DEFAULT(bool, isImmediate, false)

//ImmediateListener 기본 ArgType
#define IMMEDIATE_LISTENER_BASE_ARG DEFINE_ARG_DEFAULT(bool, isNotifyChain, false)


#define __ARGS_DEFERRED_SIGNATURE_SEQ_(_ARGS_SIGNATURE_SEQ_) \
DEPLOY_ARG_TYPES(_ARGS_SIGNATURE_SEQ_ DEFERRED_LISTENER_BASE_ARG)

#define __ARGS_IMMEDIATELY_SIGNATURE_SEQ_(_ARGS_SIGNATURE_SEQ_) \
DEPLOY_ARG_TYPES(_ARGS_SIGNATURE_SEQ_ IMMEDIATE_LISTENER_BASE_ARG)


#define __DEFINE_LISTENER_BASE(_NAME_, _ARGS_SIGNATURE_SEQ_, _DEC_ARGS_FN_)\
struct I##_NAME_##Listener{\
DISALLOW_CREATE_INSTANCE(I##_NAME_##Listener);\
public:\
    virtual ~I##_NAME_##Listener() {}\
    virtual void On##_NAME_##(_DEC_ARGS_FN_(_ARGS_SIGNATURE_SEQ_)) = 0;\
}

#define NO_DEFINE_LISTENER_ARGS

//지연형식의 Listener를 선언합니다.
#define DEFINE_LISTENER_DEFERRED(_NAME_, _ARGS_SIGNATURE_SEQ_)\
__DEFINE_LISTENER_BASE(_NAME_, _ARGS_SIGNATURE_SEQ_, __ARGS_DEFERRED_SIGNATURE_SEQ_)

//즉시형식의 Listener를 선언합니다.
#define DEFINE_LISTENER_IMMEDIATELY(_NAME_, _ARGS_SIGNATURE_SEQ_)\
__DEFINE_LISTENER_BASE(_NAME_##Immediately, _ARGS_SIGNATURE_SEQ_, __ARGS_IMMEDIATELY_SIGNATURE_SEQ_)

//지연, 즉시 타입의 Listener Type을 동시에 정의 합니다.
#define DEFINE_LISTENERS(_NAME_, _ARGS_SIGNATURE_SEQ_) \
DEFINE_LISTENER_DEFERRED(_NAME_, _ARGS_SIGNATURE_SEQ_);\
DEFINE_LISTENER_IMMEDIATELY(_NAME_, _ARGS_SIGNATURE_SEQ_)