# 공통 환경변수를 정의하기 위한 모듈파일

cmake_minimum_required(VERSION 3.7)


# name section
set(LAB_INSTALLED_DIR_NAME Installed CACHE STRING "")
set(LAB_INSTALLED_BINARY_DIR_NAME bin CACHE STRING "")
set(LAB_INSTALLED_LIB_DIR_NAME lib CACHE STRING "")
set(LAB_INSTALLED_PRE_DIR_NAME Pre CACHE STRING "")


# path section
set(LAB_INSTALLED_PATH 
    "${CMAKE_CURRENT_LIST_DIR}/../${LAB_INSTALLED_DIR_NAME}" 
    CACHE PATH ""
)
set(LAB_INSTALLED_BINARY_PATH 
    "${LAB_INSTALLED_PATH}/${LAB_INSTALLED_BINARY_DIR_NAME}" 
    CACHE PATH ""
)
set(LAB_INSTALLED_LIB_PATH 
    "${LAB_INSTALLED_PATH}/${LAB_INSTALLED_LIB_DIR_NAME}"
    CACHE PATH ""
)
set(LAB_INSTALLED_PRE_PATH 
    "${LAB_INSTALLED_PATH}/${LAB_INSTALLED_PRE_DIR_NAME}" 
    CACHE PATH ""
)